# Generated by Django 5.2 on 2025-05-07 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medicine_image_url_medicine_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Дары', 'verbose_name_plural': 'Дарылар'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Буйрутма', 'verbose_name_plural': 'Буйрутмалар'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Буйрутманын элементи', 'verbose_name_plural': 'Буйрутманын элементтери'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/', verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Дарынын аталышы'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы (сом)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Калдыгы (даана)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Түзүлгөн убактысы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Кардардын аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кардардын телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Жаңы', 'Жаңы'), ('Иштетүүдө', 'Иштетүүдө'), ('Жолдо', 'Жолдо'), ('Жеткирилди', 'Жеткирилди'), ('Аткарылбады', 'Аткарылбады')], default='Жаңы', max_length=50, verbose_name='Статусу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Жалпы баасы (сом)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicine', verbose_name='Дары'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Буйрутма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Буйрутма учурундагы баасы'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Саны'),
        ),
    ]
