# Generated by Django 5.2 on 2025-05-07 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_medicine_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категориянын аталышы')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг (автоматтык)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Категориянын сүрөтү')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Кошулган күнү'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Сунушталган товар'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган күнү'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='api.category', verbose_name='Категориясы'),
        ),
    ]
